name: Trigger auto deployment for aresai-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aresai-frontend-AutoDeployTrigger-d9b23309-4eda-4b4a-90d1-276cb66e3456.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARESAIFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARESAIFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARESAIFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend
          registryUrl: docker.io
          registryUsername: ${{ secrets.ARESAIFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ARESAIFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: aresai-frontend
          resourceGroup: Ares_Ai-the-stress-test-engine
          imageToBuild: docker.io/lindgeci/aresai-frontend:prod
          buildArguments: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}


