name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend-changed: ${{ steps.paths-filter.outputs.backend }}
      frontend-changed: ${{ steps.paths-filter.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check changed paths
        uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/deploy-azure.yml'
            frontend:
              - 'frontend/**'
              - '.github/workflows/deploy-azure.yml'

  deploy-api:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend-changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARESAIAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARESAIAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARESAIAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          registryUrl: docker.io
          registryUsername: ${{ secrets.ARESAIAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ARESAIAPI_REGISTRY_PASSWORD }}
          containerAppName: aresai-api
          resourceGroup: AresAI
          imageToBuild: lindgeci/aresai-api:${{ github.sha }}

  deploy-web:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARESAIWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARESAIWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARESAIWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend
          registryUrl: docker.io
          registryUsername: ${{ secrets.ARESAIWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ARESAIWEB_REGISTRY_PASSWORD }}
          containerAppName: aresai-web
          resourceGroup: AresAI
          imageToBuild: lindgeci/aresai-web:${{ github.sha }}
          buildArguments: |
            VITE_API_URL=https://aresai-api.thankfulbush-10967590.germanywestcentral.azurecontainerapps.io/api/v1
            VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
